### ISSUE TITLE
CancellationToken

### ISSUE THREAD

**Issue by amilcar-dev** [michelcedric/StructuredMinimalApi#38]
Hello!
Is it possible to work with cancellation token on the request?
Thanks for the project

**Comment by kavatari** [comment]
Did you try it this way? @amilcar-dev 
`IEndpoint<MyResponseObject, MyRequestObject, CancellationToken>`

**Comment by michelcedric** [comment]
Hi
As refer here 
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0#special-types
You can use Cancellation token directly manage by minimal api SDK.

You can find an example here 
https://github.com/michelcedric/StructuredMinimalApi/blob/master/StructuredMinimalApi/Application/Todos/Commands/CreateTodo/CreateTodoEndpoint.cs#L24
